CharacterId: 10012
title:
  - GroupId: 1001202
    FavorScheduleId: 100122
    CharacterId: 10012
    TextJp: トレーナー参上！
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1001203
    FavorScheduleId: 100123
    CharacterId: 10012
    TextJp: トレーナーと共に
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1001205
    FavorScheduleId: 100125
    CharacterId: 10012
    TextJp: トレーナーも一緒に
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1001206
    FavorScheduleId: 100126
    CharacterId: 10012
    TextJp: デート
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 100120010
    Id: 872
    CharacterId: 10012
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 안녕하세요. 트레이너.
    MessageJP: おはようございます、トレーナー
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120020
    Id: 873
    CharacterId: 10012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120030
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 혹시 오늘 시간 괜찮으실까요?
    MessageJP: 今日、お時間大丈夫でしょうか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120030
    Id: 874
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 응, 무슨 일이야?
    MessageJP: うん、どうしたの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120030
    Id: 875
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 딱히 바쁘지는 않아.
    MessageJP: 特に忙しくないから大丈夫だよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120040
    Id: 876
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 네, 다름이 아니라.
    MessageJP: はい、実は、
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120040
    Id: 877
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 이전에 약속드렸던 트레이닝용 시간표를 준비했습니다.
    MessageJP: この前お話していた、トレーニングメニューができたんです
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120050
    Id: 878
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 가능하다면 오늘 확인받고 싶은데, 헬스장으로 와주실 수 있을까요?
    MessageJP: よろしければ確認をしていただきたくて、ジムまで来ていただけませんか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120050
    Id: 879
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100122
    NextGroupId: 100120060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 기다리고 있겠습니다.
    MessageJP: お待ちしています！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120060
    Id: 880
    CharacterId: 10012
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100120050
    PreConditionFavorScheduleId: 100122
    FavorScheduleId: 0
    NextGroupId: 100120070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 트레이너, 혹시 이번 주말에 바쁘신가요?
    MessageJP: トレーナー、今週末はお忙しいでしょうか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120070
    Id: 881
    CharacterId: 10012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120080
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 괜찮으시면 저와 함께 쇼핑몰에 가지 않으시겠습니까?
    MessageJP: よろしければ私と一緒に、ショッピングモールに行きませんか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120080
    Id: 882
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그래, 좋아.
    MessageJP: ぜひぜひ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120080
    Id: 883
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무엇을 사려고?
    MessageJP: 何を買うの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120090
    Id: 884
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 감사합니다, 트레이너.
    MessageJP: ありがとうございます！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120100
    Id: 885
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 단백질 보충제를 사려고 하는 데 트레이너의 조언이 필요합니다.
    MessageJP: プロテインを買いたいので、トレーナーからアドバイスを頂ければと
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120100
    Id: 886
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100123
    NextGroupId: 100120110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 쇼핑몰에서 기다리겠습니다.
    MessageJP: それでは、ショッピングモールでお待ちしておりますね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120110
    Id: 887
    CharacterId: 10012
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100120100
    PreConditionFavorScheduleId: 100123
    FavorScheduleId: 0
    NextGroupId: 100120120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 트레이너, 오늘은 제가 트레이너를 위해 특별히 준비한 것이 있습니다.
    MessageJP: トレーナー。今日はトレーニングのために、特別なものを準備しました
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120120
    Id: 888
    CharacterId: 10012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100125
    NextGroupId: 100120130
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 오늘 오후 헬스장에서 뵙겠습니다.
    MessageJP: 今日の午後、ジムでお会いしましょう
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120130
    Id: 889
    CharacterId: 10012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100120120
    PreConditionFavorScheduleId: 100125
    FavorScheduleId: 0
    NextGroupId: 100120140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 트레이너.
    MessageJP: お疲れ様でした、トレーナー
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120130
    Id: 890
    CharacterId: 10012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 몸은 좀 어떠신가요?
    MessageJP: 身体の調子はいかがですか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120140
    Id: 891
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 응. 괜찮아.
    MessageJP: うん、何とかね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120140
    Id: 892
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 으으윽, 근육이….
    MessageJP: 筋肉が、悲鳴を……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120150
    Id: 893
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120170
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 역시 트레이너, 건강하시군요.
    MessageJP: さすがトレーナー、まだまだいけそうですね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120160
    Id: 894
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 운동이 조금 과했나 보군요.
    MessageJP: ちょっと強度が高かったかもしれませんね……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120160
    Id: 895
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120170
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 다음에 만나면 제가 스트레칭을 돕겠습니다.
    MessageJP: 次にお会いした時に、ストレッチのお手伝いをしますね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120170
    Id: 896
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 참, 아마 지금쯤이면 트레이너의 사무실에
    MessageJP: そうだ、おそらくそろそろトレーナーの事務所に、
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120170
    Id: 897
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 제가 보낸 단백질 보충제가 도착했을 겁니다.
    MessageJP: 私がお送りしたプロテインが届いてると思います
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120180
    Id: 898
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120190
    FeedbackTimeMillisec: 1500
    MessageType: Image
    ImagePath: UIs/03_Scenario/04_ScenarioImage/Mo_Sumire_01
    MessageKR: ''
    MessageJP: ''
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120190
    Id: 899
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120200
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 하루에 4번, 잊지 마시고 챙겨 드시길 바랍니다.
    MessageJP: 一日4回、忘れずに飲んでくださいね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120200
    Id: 900
    CharacterId: 10012
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 100120190
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 트레이너.
    MessageJP: トレーナー、こんにちは
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120210
    Id: 901
    CharacterId: 10012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120220
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 괜찮다면, 이번 주말에 잠시 뵐 수 있을까요?
    MessageJP: よかったら、今週末ちょっと会えませんか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120220
    Id: 902
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120230
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 히익! 아직 근육이….
    MessageJP: その、まだ筋肉痛が……！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120220
    Id: 903
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120230
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 운동이라면 열심히 하고 있습니다!
    MessageJP: 運動してます！サボってません！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120230
    Id: 904
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120240
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 아아…… 아뇨, 트레이너.
    MessageJP: あ、いえ、その……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120230
    Id: 905
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 운동 때문은 아닙니다.
    MessageJP: 運動関連のお話ではなく……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120240
    Id: 906
    CharacterId: 10012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100120250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그렇다면 오케이!
    MessageJP: なら何でもばっちこい！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120250
    Id: 907
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 알겠습니다.
    MessageJP: ありがとうございます！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100120250
    Id: 908
    CharacterId: 10012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100126
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 그때 뵙겠습니다.
    MessageJP: それでは後ほど！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
