CharacterId: 10023
title:
  - GroupId: 1002302
    FavorScheduleId: 100232
    CharacterId: 10023
    TextJp: 海でしてはいけないこと
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1002303
    FavorScheduleId: 100233
    CharacterId: 10023
    TextJp: とある風紀委員の弱点
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1002305
    FavorScheduleId: 100235
    CharacterId: 10023
    TextJp: ちょっとしたひと時
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1002306
    FavorScheduleId: 100236
    CharacterId: 10023
    TextJp: 砂風呂
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 100230010
    Id: 100230010
    CharacterId: 10023
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 부탁 하나만 해도 될까?
    MessageJP: 先生、ひとつお願いしても良い？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230020
    Id: 100230020
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 물론이야.
    MessageJP: もちろん、何でも言って
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230020
    Id: 100230030
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무슨 부탁인데?
    MessageJP: うん、何をすれば良い？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230030
    Id: 100230040
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 다음번에 게헨나 학원을 방문할 때 자외선 차단제 하나만 사다 줘.
    MessageJP: 今度ゲヘナに来るときに、日焼け止めを買ってきて欲しくて
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230040
    Id: 100230050
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 전에 쓰던 것이 다 떨어져서 하계 합숙을 앞두고 새로 구입하려 했는데, 선도부 일이 너무 바빠서 말이야.
    MessageJP: ずっと使ってたのが無くなっちゃったから、合宿前に買おうと思ってたんだけど
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230040
    Id: 100230060
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 도통 시내에 나갈 틈을 낼 수가 없네.
    MessageJP: 思ったよりも委員会の仕事が忙しくって……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230050
    Id: 100230070
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230055
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 알겠어.
    MessageJP: 大丈夫、任せて
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230055
    Id: 100230080
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: "'씨사이드'의 선 오일이면 되지?"
    MessageJP: 「シーサイド」の日焼け止めだよね？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230060
    Id: 100230090
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 응, 그거면 괜찮아.
    MessageJP: うん、それで合ってる
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230060
    Id: 100230100
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100232
    NextGroupId: 100230070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 부탁할게.
    MessageJP: じゃあ、よろしく
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230070
    Id: 100230110
    CharacterId: 10023
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100230060
    PreConditionFavorScheduleId: 100232
    FavorScheduleId: 0
    NextGroupId: 100230080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……물건은 확실히 준비했겠지?
    MessageJP: ……準備はできたか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230080
    Id: 100230120
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 다시 한번 말하지만 다른 학생들에게는 절대로 말하면 안 돼!
    MessageJP: 念押しになるけど、絶対に他の生徒には言うなよ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230090
    Id: 100230130
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……이오리?
    MessageJP: ……イオリ？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230090
    Id: 100230140
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 이거 나한테 보낸 메시지야?
    MessageJP: これ私に送るメッセージで合ってる？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230100
    Id: 100230150
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: ……선생님?
    MessageJP: ……は？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230110
    Id: 100230160
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230120
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: ㄴ야ㅣㅓㄴㅇ랴ㅣㄴ
    MessageJP: ｊぐぁｋｌｆ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230110
    Id: 100230170
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230120
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 아, 아무것도 아니야!
    MessageJP: やっ、何でもない！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230110
    Id: 100230180
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 지금 보낸 메시지는 신경 쓰지 마.
    MessageJP: 今送ったメッセージのことは忘れて！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230120
    Id: 100230190
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100233
    NextGroupId: 100230130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그렇게 말하니 더 신경 쓰이는데…….
    MessageJP: そう言われると、尚更気になる……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230130
    Id: 100230200
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100230120
    PreConditionFavorScheduleId: 100233
    FavorScheduleId: 0
    NextGroupId: 100230140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아까는 수영 연습 도와줘서 고마워. 선생님.
    MessageJP: その……泳ぎの練習、付き合ってくれてありがと。先生
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230140
    Id: 100230210
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 덕분에 능숙하지는 않지만 어느 정도는 헤엄칠 수 있게 된 것 같아.
    MessageJP: おかげで、お世辞にも習得したとは言えないけど、何とか泳げるくらいにはなったし……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230140
    Id: 100230220
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 이제 보조 튜브는 필요 없겠지…….
    MessageJP: これで合宿に浮き輪を持っていかずに済むかも
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230150
    Id: 100230230
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 저기, 이오리.
    MessageJP: それは良かった。ところでイオリ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230160
    Id: 100230240
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230170
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: ……왜?
    MessageJP: ……何？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230170
    Id: 100230250
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 튜브에 그려진 귀여운 오리는 이오리의 취향이야?
    MessageJP: 浮き輪に描かれてたけど、イオリはアヒルさんが好きなの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230180
    Id: 100230260
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230190
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 시끄러워! 죽어!
    MessageJP: うるさい！死ねっ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230190
    Id: 100230270
    CharacterId: 10023
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100230180
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 출동이야!
    MessageJP: 先生、今どこ？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230200
    Id: 100230280
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 방금 들어온 신고에 따르면 바다의 집 앞에서 불량 학생들이 행패를 부리고 있나 봐.
    MessageJP: 連絡が入ったんだけど、どうやら海の家の近くでチンピラたちが暴れてるらしい
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230210
    Id: 100230290
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 게헨나 선도부의 스페셜리스트로서 이런 만행을 두고 볼 수는 없지!
    MessageJP: ゲヘナの風紀委員会として、放っておくわけにはいかない
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230210
    Id: 100230300
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 지금 바로 바다의 집으로 따라 나와줘.
    MessageJP: ただ相手の数も分からないし、他の風紀委員も動けないから、先生も来てほしい
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230210
    Id: 100230310
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 물에 들어가야 할지도 모르니 수영복 챙겨오는 것도 잊지 말고!
    MessageJP: あ、海に落ちるかもだし、水着の方が良いと思う！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230220
    Id: 100230320
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100235
    NextGroupId: 100230230
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……잠깐, 나도 가야 하는 거야?
    MessageJP: え、待って待って！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230230
    Id: 100230330
    CharacterId: 10023
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 100230220
    PreConditionFavorScheduleId: 100235
    FavorScheduleId: 0
    NextGroupId: 100230240
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 아까 프런트에 물어보니 한나절 넘게 숙소에 돌아오지 않았다고 하던데…….
    MessageJP: 先生。さっきフロントで、半日以上戻ってきてないって聞いたんだけど……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230240
    Id: 100230340
    CharacterId: 10023
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230250
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 지금 어디에 있어?
    MessageJP: 今はどこにいるんだ？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230250
    Id: 100230350
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230260
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 모래사장 위에 있어.
    MessageJP: 砂浜に
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230260
    Id: 100230360
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230270
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 모래사장? 거기서 뭘 하고 있는데?
    MessageJP: 砂浜？砂浜で一体何を……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230270
    Id: 100230370
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230280
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그냥 누워있어.
    MessageJP: ただ横になってる
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230280
    Id: 100230380
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230290
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: ……어째서?
    MessageJP: は……？どうして？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230280
    Id: 100230390
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230290
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니, 말하지 않아도 알겠어.
    MessageJP: いや、言わなくて良い。分かった
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230290
    Id: 100230400
    CharacterId: 10023
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100230300
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 지금 체포하러 갈게.
    MessageJP: 手錠を探してすぐ行くから、そこから動かないで
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100230300
    Id: 100230410
    CharacterId: 10023
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100236
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 잠깐, 무슨 생각을 한 거야?
    MessageJP: 待って、何を想像してるの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
