CharacterId: 10032
title:
  - GroupId: 1003202
    FavorScheduleId: 100322
    CharacterId: 10032
    TextJp: 先生のためにプレゼント
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1003203
    FavorScheduleId: 100323
    CharacterId: 10032
    TextJp: 正月には正月らしく！
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1003205
    FavorScheduleId: 100325
    CharacterId: 10032
    TextJp: 激しい戦い
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 100320010
    Id: 100320010
    CharacterId: 10032
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님~ 선생님~
    MessageJP: 先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320020
    Id: 100320020
    CharacterId: 10032
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 새해 복 많이 받아~!
    MessageJP: あらためて、明けましておめでとー！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320030
    Id: 100320030
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 어, 벌써…. 새해인가?
    MessageJP: いつの間にお正月だ……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320030
    Id: 100320040
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 응…. 무츠키도 새해 복 많이 받아.
    MessageJP: うん、明けましておめでとう
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320040
    Id: 100320050
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 흐응, 뭐야~ 선생님의 반응, 재미없어~
    MessageJP: えー、何その先生のリアクション。つまんな～い
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320040
    Id: 100320060
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 뭐, 그런 평소에도 흐느적흐느적하는 선생님이라도 불타오를 수 있도록.
    MessageJP: しょうがないなぁ……そんなふにゃふにゃな先生でも一気に燃え上がるような
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320050
    Id: 100320070
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 내가 또 엄청난 걸 준비했지만 말이야!
    MessageJP: 「ものすごく楽しいこと」を用意してあげる！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320060
    Id: 100320080
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 흐느적흐느적…?
    MessageJP: ふにゃふにゃ……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320060
    Id: 100320090
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무츠키가 준비한, 거?
    MessageJP: 「ものすごく楽しいこと」……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320070
    Id: 100320100
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320080
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 잔뜩 기대하고 있어~ 선생님!
    MessageJP: じゃあ楽しみにしててね、先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320080
    Id: 100320110
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 응…? 무츠키?
    MessageJP: え、えっ……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320090
    Id: 100320120
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100322
    NextGroupId: 100320100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 저기요…?
    MessageJP: ムツキ……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320100
    Id: 100320130
    CharacterId: 10032
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100320090
    PreConditionFavorScheduleId: 100322
    FavorScheduleId: 0
    NextGroupId: 100320110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 혹시 소원 같은 거 있어?
    MessageJP: 先生って、新年のお願いごともう決めた？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320110
    Id: 100320140
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 당연히 있지!
    MessageJP: もちろん！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320110
    Id: 100320150
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 음, 딱히 없어.
    MessageJP: そういえばまだ……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320120
    Id: 100320160
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아하~ 역시 그렇구나.
    MessageJP: ふーん、そうなんだ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320120
    Id: 100320170
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320140
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 응, 하긴 평범하게 생각하면 소원 한둘쯤은 가지고 있을 테니까~
    MessageJP: 先生のお願いごと、気になるな―
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320130
    Id: 100320180
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 어라~? 그래?
    MessageJP: あ、そうなんだ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320130
    Id: 100320190
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 흐응~ 뭐, 상관은 없지만!
    MessageJP: まあ、今からゆっくり決めれば良いんじゃない？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320140
    Id: 100320200
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 가자! 선생님! 소원 빌러!
    MessageJP: とりあえず先生、行こう！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320150
    Id: 100320210
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 응? 갑자기 무슨 뜻이야?
    MessageJP: えっと、どこに？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320160
    Id: 100320220
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 모처럼의 새해잖아?
    MessageJP: せっかくお正月なんだから決まってるでしょ？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320160
    Id: 100320230
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320170
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 기왕이면 거기에 맞춘 이벤트를 즐길 필요가 있다구?
    MessageJP: 正月なんだから、正月らしいところに行かないと！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320170
    Id: 100320240
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100323
    NextGroupId: 100320180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 자, 그러니 집합이야! 선생님!
    MessageJP: ほらほら、早く準備して！先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320180
    Id: 100320250
    CharacterId: 10032
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100320170
    PreConditionFavorScheduleId: 100323
    FavorScheduleId: 0
    NextGroupId: 100320190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님! 엄청나게 하네츠키가 하고 싶어졌어!
    MessageJP: 先生！羽根つきしよっ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320190
    Id: 100320260
    CharacterId: 10032
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 갑자기 하네츠키를……?
    MessageJP: いきなりだね……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320200
    Id: 100320270
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 지난번의 패배를, 하네츠키로 설욕해 줄 테니까!
    MessageJP: この前の敗北の屈辱、思いっきり晴らしちゃうから！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320210
    Id: 100320280
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100320220
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 그럼 승부야!
    MessageJP: さー、尋常に勝負！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320210
    Id: 100320290
    CharacterId: 10032
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100325
    NextGroupId: 100320220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 기다리고 있을게!
    MessageJP: 待ってるからね！早く早く！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320220
    Id: 100320300
    CharacterId: 10032
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100320210
    PreConditionFavorScheduleId: 100325
    FavorScheduleId: 0
    NextGroupId: 100320230
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 이번 새해에도, 선생님과 함께해서 엄청 재미있었어.
    MessageJP: 先生のおかげでお正月、すっごい楽しかった！ありがとね！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320230
    Id: 100320310
    CharacterId: 10032
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 새해에도, 그리고 앞으로도.
    MessageJP: これから先もずっと
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100320230
    Id: 100320320
    CharacterId: 10032
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 나랑 잔뜩 놀아줘야 해? 선생님♡
    MessageJP: 私とたーっくさん遊んでね、先生♡
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
