CharacterId: 13006
title:
  - GroupId: 1300602
    FavorScheduleId: 130062
    CharacterId: 13006
    TextJp: 小悪魔は遊ぶのがお好き
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1300603
    FavorScheduleId: 130063
    CharacterId: 13006
    TextJp: 人には言えない小悪魔の秘密
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1300605
    FavorScheduleId: 130065
    CharacterId: 13006
    TextJp: 小悪魔の趣味
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1300606
    FavorScheduleId: 130066
    CharacterId: 13006
    TextJp: 誰かからの特別な依頼
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 130060010
    Id: 1072
    CharacterId: 13006
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: "심심~해~! (つ\_◑▽◑)つ"
    MessageJP: "ひ～ま～！(つ\_◑▽◑)つ"
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060020
    Id: 1073
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 지금 뭐 하고 있어?
    MessageJP: 先生、今なにしてるの～？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060030
    Id: 1074
    CharacterId: 13006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 업무 중이야.
    MessageJP: 仕事中だよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060030
    Id: 1075
    CharacterId: 13006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 지금 숨 쉬고 있어.
    MessageJP: 息してるよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060040
    Id: 1076
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그래? 흐응. 그렇단 말이지.
    MessageJP: そうなの？ふーん、そっか
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060040
    Id: 1077
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 방해하면 안 되겠네.
    MessageJP: それは邪魔しちゃダメだね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060040
    Id: 1078
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 응, 열심히 일해. 선생님!
    MessageJP: じゃ、頑張ってねー先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060050
    Id: 1079
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060060
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 아하하하!!
    MessageJP: あははは！！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060050
    Id: 1080
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그렇구나~ 응! 숨 쉬는 건 완전 중요하지!
    MessageJP: そっか～うんうん！息するのめっちゃ大事だよね！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060050
    Id: 1081
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 나도 열심히 응원할게. 선생님.
    MessageJP: 私も呼吸の応援、してるからね。先生♪
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060060
    Id: 1082
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 130062
    NextGroupId: 130060070
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 힘내!
    MessageJP: じゃ、頑張ってねー！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060070
    Id: 1083
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 130060060
    PreConditionFavorScheduleId: 130062
    FavorScheduleId: 0
    NextGroupId: 130060080
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 쿠후후.
    MessageJP: くふふっ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060070
    Id: 1084
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 오늘 재미있었어~ 선생님!
    MessageJP: 今日は楽しかったね～、先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060070
    Id: 1085
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 다음에 또 잔뜩 놀자.
    MessageJP: また今度、たくさん遊ぼうね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060080
    Id: 1086
    CharacterId: 13006
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 130060070
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 오늘 한가하지?
    MessageJP: 先生、今日暇でしょ？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060090
    Id: 1087
    CharacterId: 13006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니, 바쁜데?
    MessageJP: えっと、忙しいけど……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060090
    Id: 1088
    CharacterId: 13006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그, 그걸 어떻게 알았지?!
    MessageJP: どうして分かったの！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060100
    Id: 1089
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 으응~? 바쁘다고?
    MessageJP: え～？忙しいの～？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060100
    Id: 1090
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060120
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 뭐, 그래도 상관없어!
    MessageJP: まあ、でも関係ないけどね！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060100
    Id: 1091
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060120
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 처음부터 선생님에게 선택지는 없었으니까!
    MessageJP: なぜなら、最初から先生に選択権は無いから！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060110
    Id: 1092
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 응? 그걸 어떻게 알고 있냐고?
    MessageJP: ん～？どうして？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060110
    Id: 1093
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 쿠후후, 우리 흥신소의 정보력을 얕보지 말라구~
    MessageJP: ……くふふ、うちの便利屋の情報収集能力をなめちゃダメだよ～？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060120
    Id: 1094
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 130063
    NextGroupId: 130060130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: |-
      그러니까 오늘 우리 흥신소로 놀러 와!
      (≧∇≦)ﾉ
    MessageJP: そういうわけで今日は、うちの便利屋に遊びに来てほしいな！(≧∇≦)ﾉ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060130
    Id: 1095
    CharacterId: 13006
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 130060120
    PreConditionFavorScheduleId: 130063
    FavorScheduleId: 0
    NextGroupId: 130060140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님은 혹시 취미가 있어?
    MessageJP: 先生って、何か趣味とかあるのー？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060140
    Id: 1096
    CharacterId: 13006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 물론이지.
    MessageJP: もちろん
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060140
    Id: 1097
    CharacterId: 13006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니, 딱히 취미라고 할만한 건 없는데.
    MessageJP: 趣味って言えるほどのものは無いかな……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060150
    Id: 1098
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아핫~ 역시~ 취미 생활이 있다는 건 좋은 일이야.
    MessageJP: そっか～。やっぱり、趣味があるって良いよね～
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060150
    Id: 1099
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 몰두하고 있으면 시간도 금방 지나가고.
    MessageJP: 夢中になってると、時間もすぐに過ぎていくしー
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060150
    Id: 1100
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 내가 좋아하는 분야에 대해 빠삭하게 알게 되었을 때의 성취감도 있고.
    MessageJP: 好きな分野について詳しくなると、達成感もあるし？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060150
    Id: 1101
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060170
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 응응! 즐겁지~
    MessageJP: 楽しいよね～！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060160
    Id: 1102
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 흐응, 그래애~?
    MessageJP: ふーん、そうなんだ～？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060160
    Id: 1103
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060170
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 그건 좀 아쉬울지도~
    MessageJP: それはちょっと残念かも～
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060170
    Id: 1104
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 130065
    NextGroupId: 130060180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 응, 나중에 선생님하고 취미 이야기를 하는 것도 재밌겠다~ (〇'ヮ'〇)
    MessageJP: いつか先生とそういう趣味の話をしたいな～、面白そう！(〇'ヮ'〇)
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060180
    Id: 1105
    CharacterId: 13006
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 130060170
    PreConditionFavorScheduleId: 130065
    FavorScheduleId: 0
    NextGroupId: 130060190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 우리 흥신소에 특별한 의뢰가 들어왔어!
    MessageJP: 先生、うちの便利屋に変わった依頼が届いたの！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060190
    Id: 1106
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 이게 또 어마어마하거든?
    MessageJP: これがまた、すっごい変な依頼でさ～？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060190
    Id: 1107
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060200
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 거기다 또 흥미진진하거든?
    MessageJP: でも同時にすっごく面白そうでね～？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060200
    Id: 1108
    CharacterId: 13006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무츠키가 어마어마하다고 할 정도면 대체…….
    MessageJP: ムツキがすっごい変って言うほどの依頼っていったい……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060200
    Id: 1109
    CharacterId: 13006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무츠키가 흥미진진하다고 할 정도면 대체…….
    MessageJP: ムツキがすっごく面白そうって言うような依頼っていったい……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060210
    Id: 1110
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130060220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 으음~! 됐으니까.
    MessageJP: ん～、まあまあ！細かいことは置いといてさ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060210
    Id: 1111
    CharacterId: 13006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 130066
    NextGroupId: 130060220
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 도와줘, 선생님~!
    MessageJP: 先生に手伝ってほしいな～？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060220
    Id: 1112
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 130060210
    PreConditionFavorScheduleId: 130066
    FavorScheduleId: 0
    NextGroupId: 130060230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 오늘 하루, 즐거웠어. 선생님~!
    MessageJP: 今日は一日楽しかったよ～先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060230
    Id: 1113
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 다음번엔 완벽하게 성공해 보일 테니까.
    MessageJP: 次は絶っ対に成功させてみせるから、
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130060230
    Id: 1114
    CharacterId: 13006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 각오하라구~! ＼( 'ω') /
    MessageJP: 覚悟しててね～！＼( 'ω') /
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
