student_id: 10024

chats:
  before:
    - type: chat
      text:
        zh: 我预计会出远门一段时间
        jp: しばらく遠出する予定なの
      sender: student
    - type: chat
      text:
        zh: 和大家也已经打过招呼了
        jp: みんなにもメッセージは送っておいたんだけど
      sender: student
    - type: chat
      text:
        zh: 想着也和老师说一声比较好
        jp: 先生にも伝えておこうかなって
      sender: student
    - type: option
      options:
        - text:
            zh: ……出远门？
            jp: ……遠出？
          selection: 1
        - text:
            zh: 未定
            jp: 未定
          selection: 1
      sender: teacher
    - type: diversion
      variations:
        - selection: 1
          replies:
            - type: chat
              text:
                zh: 没关系，不是什么大事
                jp: 大丈夫、大したことじゃない
              sender: student
            - type: chat
              text:
                zh: 那么，再见了。老师
                jp: じゃあ、またね。先生
              sender: student
    - type: link
      text:
        zh: 前往白子（骑行）的羁绊剧情
        jp: 白子（ライディング）の絆ストーリーへ
      link: 10024_story_01
  after:
    - type: chat
      text:
        zh: 老师
        jp: 先生
      sender: student
    - type: chat
      text:
        zh: 刚好在休息，所以就试着联系了
        jp: ちょうど休むタイミングだったから，連絡してみた
      sender: student
    - type: option
      options:
        - text:
            zh: 难道说，已经骑了相当远了吗……？
            jp: もしかして，もう結構遠くまで行った感じ……？
          sender: teacher
          selection: 1
        - text:
            zh: 未定
            jp: 未定
          sender: teacher
          selection: 1
    - type: diversion
      variations:
        - selection: 1
          replies:
            - type: chat
              text:
                zh: 嗯？
                jp: ん？
              sender: student
    - type: chat
      text:
        zh: 没有，我还在刚刚和老师在一起的地方附近
        jp: ううん，まださっき先生といた場所の近く
      sender: student
    - type: chat
      text:
        zh: 正好是等红灯的空闲时间，所以就和老师联系了
        jp: ちょうど信号で，足を止めたから連絡してみた
      sender: student
    - type: chat
      text:
        zh: ……诶？
        jp: ……あれ？
      sender: student
    - type: chat
      text:
        zh: 难道说所谓的停下来，不是这个时候吗？
        jp: もしかして止まるたびにって，こういう意味じゃない？
      sender: student
    - type: chat
      text:
        zh: 抱歉，是我弄错了
        jp: ……ごめん，勘違いしてた
      sender: student
    - type: chat
      text:
        zh: 那，嗯……等我下车休息的时候，再和老师联系吧
        jp: じゃあ，えっと……休憩とかで自転車を降りたら，その度に連絡するね
      sender: student
